### PR TITLE
Create a function to import a single expriment given an injection coordinate issue #120

### PR DESCRIPTION
**Pull request by madgtroy1**
**Why this pull request ?**
New script needed : allow a user to import allen experiments given an 3D-voxel coordinate in his data space

**What's in this pull request ?**
- `m2m_experiments_finder.py` : the new scriptconcerned by this issue
- its sphinx documentation .rst
- a quick changed in the documentation of `m2m_crossing_finder.py` to replace MI-BRAIN by UDS

**What does the script do ?**
- it searches a given number (---nb_of_exps) of projection density maps like `m2m_import_proj_density.py` given a 3D-voxel coordinate in UDS (x y  z) either by injection or spatial search (--injection, --spatial). 
- Downloads them
- Aligns them to the UDS
- Saves them in a folder named depending of the research method, the coordinates given and the resolution
- Names each projection map according to the `m2m_import_proj_density.py` standard.

**Discussion**
The fact that this script import the projection maps seems rendondant. What about returning only the ids of experiments rather that downloading them? Because `m2m_import_proj_density.py` can already do the importation and have many usefull options.

### CODE REVIEW

**Comment by joe-from-mtl** [comment]
> The fact that this script import the projection maps seems rendondant. What about returning only the ids of experiments rather that downloading them? Because `m2m_import_proj_density.py` can already do the importation and have many usefull options.

To avoid this redundancy, could we modify the `m2m_import_proj_density.py` script to allow a single input location instead of the mandatory 2 positions? Or maybe we should change the `m2m_import_proj_density.py` script name to better reflect that it's function is to download the proj. expriments for crossing experiments.

**Review by joe-from-mtl — APPROVED** [review]

**Comment by madgtroy1** [comment]
> > The fact that this script import the projection maps seems rendondant. What about returning only the ids of experiments rather that downloading them? Because `m2m_import_proj_density.py` can already do the importation and have many usefull options.
> 
> To avoid this redundancy, could we modify the `m2m_import_proj_density.py` script to allow a single input location instead of the mandatory 2 positions? Or maybe we should change the `m2m_import_proj_density.py` script name to better reflect that it's function is to download the proj. expriments for crossing experiments.

I apologize for any confusion in our discussion. It seems we have been discussing different scripts and their functionalities. 

The `m2m_crossing_finder.py` script performs a crossing study by taking two positions as parameters. On the other hand, the `m2m_import_proj_density.py` that you've mentioned allows the user to download various files related to an Allen experiment identifier : the projection map, a sphere at the injection center, a JSON file with further informations, and a binarized map.

Here a clarification of what i meant:

Regarding the new script introduced in this PR (`m2m_experiments_finder`), it enables the user to download one or multiple experiments based on a single position, but it currently only provides the projection map and not the additional files available in `m2m_import_proj_density.py`. If we want this script to provide more, it will create the redundancy i was mentionning.

Considering this, I suggest modifying this new script to only return the experiment identifiers found. The documentation can then inform users that these identifiers can be used with the `m2m_import_proj_density.py` script to download the desired files, thus avoiding redundancy and clearly distinguishing the functionalities of each script. 

But in any case we should confirm with Laurent ;)

**Comment by joe-from-mtl** [comment]
Ok, now I understand. I agree with you, `m2m_crossing_finder.py` should return a file with the list of experiment ids and `m2m_import_proj_density.py` should be used to download them.

**Comment by madgtroy1** [comment]
> Ok, now I understand. I agree with you, `m2m_crossing_finder.py` should return a file with the list of experiment ids, and `m2m_import_proj_density.py` should be used to download them.

## Why this pull request?
The new script needed: allow a user to import Allen experiments ids given a 3D-voxel coordinate in his data space (UDS)

## What's in this pull request?
- `m2m_experiments_finder.py`: the new script concerned by this issue
- its sphinx documentation .rst
- a new option in `m2m_import_proj_density.py` to allow the user to use a CSV file as an input (`--ids_csv`)
- `id` option is now `--id`, mutually exclusive with `--ids_csv`
- a quick change in the documentation of `m2m_crossing_finder.py` to replace MI-BRAIN to UDS

## What does the script do?
- it searches a given number (---nb_of_exps) of projection density maps like m2m_import_proj_density.py given a 3D-voxel coordinate in UDS (x y z) either by injection or spatial search (--injection, --spatial).
- Saved the identifiers found in a CSV file.

## Script interaction
IDs found with `m2m_experiments_finder.py` can be use as an input to `m2m_import_proj_density.py` 

## What to review?
- Code standard PEP8/Flake8
- Spelling mistakes in documentation
- Potential bugs
- Code lisibility

**Review by joe-from-mtl — APPROVED** [review]

**Pull request merged**
